<x-layouts.app>
<div class="space-y-6" data-school-class-module="material-you-3"><x-admin.page-header kicker="Master Akademik" title="Kelas {{ strtoupper($schoolLevel) }}" description="Kelola kelas manual dan kelas hasil sinkronisasi tingkat rombel." :count="$classes->total().' kelas'"><a href="{{ route('admin.school-classes.create', $schoolLevel) }}" class="admin-button-primary px-4 py-2 text-sm"><i class="fas fa-plus mr-2"></i>Tambah Kelas</a></x-admin.page-header>
@if(session('success'))<div class="admin-alert-success rounded-2xl p-4 text-sm font-semibold">{{ session('success') }}</div>@endif @if(session('error'))<div class="admin-alert-danger rounded-2xl p-4 text-sm font-semibold">{{ session('error') }}</div>@endif
<div class="admin-glass-panel overflow-hidden"><div class="overflow-x-auto"><table class="admin-table w-full"><thead><tr><th class="px-5 py-4 text-left">Nama Kelas</th><th class="px-5 py-4 text-left">Tingkat</th><th class="px-5 py-4 text-left">Siswa</th><th class="px-5 py-4 text-left">Status</th><th class="px-5 py-4 text-right">Aksi</th></tr></thead><tbody>@forelse($classes as $class)<tr><td class="px-5 py-4 font-bold">{{ $class->name }}</td><td class="px-5 py-4 text-sm">{{ $class->grade_level ?: '—' }}</td><td class="px-5 py-4 text-sm">{{ $class->students_count }} siswa</td><td class="px-5 py-4"><span class="{{ $class->is_active ? 'admin-status-success' : 'admin-status-info' }} px-3 py-1 text-xs">{{ $class->is_active ? 'Aktif' : 'Nonaktif' }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><a href="{{ route('admin.school-classes.edit', [$schoolLevel, $class]) }}" class="admin-row-action admin-row-action-edit" title="Edit kelas" aria-label="Edit kelas {{ $class->name }}"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"></path>
</svg></a><form method="POST" action="{{ route('admin.school-classes.destroy', [$schoolLevel, $class]) }}" x-data="{}" @submit.prevent="$dispatch('admin-confirm', { title: 'Hapus Kelas', message: 'Kelas hanya dapat dihapus bila tidak memiliki siswa.', confirmText: 'Hapus', variant: 'danger', form: $el })">@csrf @method('DELETE')<button class="admin-row-action admin-row-action-delete" title="Hapus kelas" aria-label="Hapus kelas {{ $class->name }}"><svg class="h-5 w-5" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"></path>
</svg></button></form></div></td></tr>@empty<tr><td colspan="5"><x-admin.empty-state icon="fas-chalkboard" title="Belum ada kelas" hint="Tambahkan kelas atau sinkronkan data siswa." /></td></tr>@endforelse</tbody></table></div>@if($classes->hasPages())<div class="admin-panel-footer">{{ $classes->links() }}</div>@endif</div></div>
</x-layouts.app>
