<x-layouts.mobile title="{{ $record->exists ? 'Edit Catatan BK' : 'Catatan BK Baru' }}" backUrl="{{ $record->exists ? route('attendance.bk.show',$record) : route('attendance.bk.index') }}" isSheet="true">
<form method="POST" enctype="multipart/form-data" action="{{ $record->exists ? route('attendance.bk.update',$record) : route('attendance.bk.store') }}" class="space-y-4">@csrf @if($record->exists) @method('PUT') @endif
<h1 class="font-display text-xl font-black theme-text-main">{{ $record->exists?'Edit':'Buat' }} Catatan BK</h1>@if($errors->any())<div class="rounded-2xl bg-red-50 p-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
<div class="glass-card theme-border space-y-4 rounded-[24px] p-5">
@include('attendance.bk.partials.student-combobox')
@include('attendance.bk.partials.related-students-combobox')
<label class="block text-xs font-bold">Jenis<select id="record_type" name="record_type" class="theme-input mt-2 w-full rounded-2xl p-3"><option value="violation" @selected(old('record_type',$record->record_type)==='violation')>Pelanggaran</option><option value="counseling" @selected(old('record_type',$record->record_type)==='counseling')>Konseling</option></select></label>
<label class="block text-xs font-bold">Kategori<select id="category_id" name="category_id" class="theme-input mt-2 w-full rounded-2xl p-3"><option value="">Lainnya</option>@foreach($categories as $c)<option data-type="{{$c->record_type}}" data-severity="{{$c->default_severity}}" value="{{$c->id}}" @selected(old('category_id',$record->category_id)==$c->id)>{{$c->name}}</option>@endforeach</select></label>
<label class="block text-xs font-bold">Topik lainnya<input name="custom_topic" value="{{old('custom_topic',$record->custom_topic)}}" class="theme-input mt-2 w-full rounded-2xl p-3"></label>
<label class="block text-xs font-bold">Waktu<input type="datetime-local" required name="occurred_at" value="{{old('occurred_at',$record->occurred_at?->format('Y-m-d\TH:i') ?? now()->format('Y-m-d\TH:i'))}}" class="theme-input mt-2 w-full rounded-2xl p-3"></label>
<div id="violation"><label class="block text-xs font-bold">Tingkat<select id="severity" name="severity" class="theme-input mt-2 w-full rounded-2xl p-3">@foreach(['light'=>'Ringan','medium'=>'Sedang','heavy'=>'Berat'] as $v=>$l)<option value="{{$v}}" @selected(old('severity',$record->severity)===$v)>{{$l}}</option>@endforeach</select></label><label class="mt-4 block text-xs font-bold">Kronologi<textarea name="chronology" class="theme-input mt-2 w-full rounded-2xl p-3">{{old('chronology',$record->chronology)}}</textarea></label><label class="mt-4 block text-xs font-bold">Tindakan<textarea name="action_taken" class="theme-input mt-2 w-full rounded-2xl p-3">{{old('action_taken',$record->action_taken)}}</textarea></label></div>
<div id="counseling"><label class="block text-xs font-bold">Isi konseling<textarea name="counseling_content" class="theme-input mt-2 w-full rounded-2xl p-3">{{old('counseling_content',$record->counseling_content)}}</textarea></label><label class="mt-4 block text-xs font-bold">Hasil<textarea name="counseling_result" class="theme-input mt-2 w-full rounded-2xl p-3">{{old('counseling_result',$record->counseling_result)}}</textarea></label></div>
<label class="block text-xs font-bold">Rencana tindak lanjut<textarea name="follow_up_plan" class="theme-input mt-2 w-full rounded-2xl p-3">{{old('follow_up_plan',$record->follow_up_plan)}}</textarea></label>
<label class="block text-xs font-bold">Status<select name="status" class="theme-input mt-2 w-full rounded-2xl p-3">@foreach(['new'=>'Baru','in_progress'=>'Diproses','waiting_follow_up'=>'Menunggu tindak lanjut','completed'=>'Selesai'] as $v=>$l)<option value="{{$v}}" @selected(old('status',$record->status??'new')===$v)>{{$l}}</option>@endforeach</select></label>
<label class="block text-xs font-bold">Lampiran privat (maks. 5)<input type="file" multiple name="attachments[]" class="theme-input mt-2 w-full rounded-2xl p-3"></label>
</div><button class="theme-btn-submit w-full rounded-full p-4 font-bold">Simpan</button></form>
<script>const t=document.querySelector('#record_type'),v=document.querySelector('#violation'),c=document.querySelector('#counseling'),cat=document.querySelector('#category_id');function sync(){v.hidden=t.value!=='violation';c.hidden=t.value!=='counseling';[...cat.options].forEach(o=>o.hidden=o.dataset.type&&o.dataset.type!==t.value)}t.onchange=sync;cat.onchange=()=>{let o=cat.selectedOptions[0];if(o.dataset.severity)document.querySelector('#severity').value=o.dataset.severity};sync()</script>
</x-layouts.mobile>