@php($levelLabel = strtoupper($schoolLevel))
<div class="grid gap-5 md:grid-cols-2">
    <div class="md:col-span-2"><label for="nama_lengkap" class="admin-label">Nama Lengkap</label><input id="nama_lengkap" name="nama_lengkap" class="admin-field p-3" value="{{ old('nama_lengkap', $student?->nama_lengkap) }}" required>@error('nama_lengkap')<p class="admin-hint admin-text-danger">{{ $message }}</p>@enderror</div>
    <div><label for="nisn" class="admin-label">NISN</label><input id="nisn" name="nisn" class="admin-field p-3" value="{{ old('nisn', $student?->nisn) }}" inputmode="numeric">@error('nisn')<p class="admin-hint admin-text-danger">{{ $message }}</p>@enderror</div>
    <div><label for="nik" class="admin-label">NIK</label><input id="nik" name="nik" class="admin-field p-3" value="{{ old('nik', $student?->nik) }}" inputmode="numeric">@error('nik')<p class="admin-hint admin-text-danger">{{ $message }}</p>@enderror</div>
    <div><label for="school_class_id" class="admin-label">Kelas {{ $levelLabel }}</label><select id="school_class_id" name="school_class_id" class="admin-field p-3"><option value="">Belum ditentukan</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected(old('school_class_id', $student?->school_class_id) == $class->id)>{{ $class->name }}</option>@endforeach</select></div>
    <div><label for="status" class="admin-label">Status</label><select id="status" name="status" class="admin-field p-3">@foreach(\App\Models\Student::STATUSES as $status)<option @selected(old('status', $student?->status ?? 'Aktif') === $status)>{{ $status }}</option>@endforeach</select></div>
    <div><label for="tempat_lahir" class="admin-label">Tempat Lahir</label><input id="tempat_lahir" name="tempat_lahir" class="admin-field p-3" value="{{ old('tempat_lahir', $student?->tempat_lahir) }}"></div>
    <div><label for="tanggal_lahir" class="admin-label">Tanggal Lahir</label><input type="date" id="tanggal_lahir" name="tanggal_lahir" class="admin-field p-3" value="{{ old('tanggal_lahir', $student?->tanggal_lahir?->format('Y-m-d')) }}"></div>
    <div><label for="jenis_kelamin" class="admin-label">Jenis Kelamin</label><select id="jenis_kelamin" name="jenis_kelamin" class="admin-field p-3"><option value="">Tidak ditentukan</option><option value="L" @selected(old('jenis_kelamin', $student?->jenis_kelamin) === 'L')>Laki-laki</option><option value="P" @selected(old('jenis_kelamin', $student?->jenis_kelamin) === 'P')>Perempuan</option></select></div>
    <div><label for="no_telepon" class="admin-label">Nomor Telepon</label><input id="no_telepon" name="no_telepon" class="admin-field p-3" value="{{ old('no_telepon', $student?->no_telepon) }}"></div>
    <div class="md:col-span-2"><label for="alamat" class="admin-label">Alamat</label><textarea id="alamat" name="alamat" rows="3" class="admin-field p-3">{{ old('alamat', $student?->alamat) }}</textarea></div>
    @foreach(['kebutuhan_khusus'=>'Kebutuhan Khusus','disabilitas'=>'Disabilitas','nomor_kip_pip'=>'Nomor KIP/PIP','nama_ayah_kandung'=>'Nama Ayah Kandung','nama_ibu_kandung'=>'Nama Ibu Kandung','nama_wali'=>'Nama Wali'] as $field=>$label)<div><label for="{{ $field }}" class="admin-label">{{ $label }}</label><input id="{{ $field }}" name="{{ $field }}" class="admin-field p-3" value="{{ old($field, $student?->{$field}) }}"></div>@endforeach
</div>
<div class="flex justify-end gap-3 pt-6"><a href="{{ route('admin.students.index', $schoolLevel) }}" class="admin-button-secondary px-5 py-3 text-sm">Batal</a><button class="admin-button-primary px-5 py-3 text-sm">Simpan Siswa</button></div>
